services:
  db:
    image: postgres:latest

    container_name: jardinier-backend-db
    restart: always

    environment:
      POSTGRES_DB: jardinier
      POSTGRES_USER: jardinier
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../jardinier_postgres_data:/var/lib/postgresql/data
